cproject/cproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('idea/', include('idea.urls', namespace='posts'))
]

cproject/idea/urls.py
from django.urls import path
from .views import *

app_name = 'idea'

urlpatterns = [
    path('', post_view, name='post-list'),
    path('like/', like_post, name='like-post'),
    path('add-idea/', add_idea, name='add_idea'),
]

cproject/idea/models.py
from django.db import models
from django.contrib.auth.models import User

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)




class Post(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
    updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')

    def __str__(self):
        return str(self.title)

    @property
    def num_likes(self):
        return self.liked.all().count()

    class Meta:
        ordering = ['-created_at']


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

    def __str__(self):
        return str(self.post)

cproject/idea/forms.py
from django import forms
from .models import *


class IdeaForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body']
        widgets = {
                'title': forms.TextInput(attrs={'class': 'form-control'}),
                'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            }

cproject/idea/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .forms import *
from .models import *



def post_view(request):
    qs = Post.objects.all()
    user = request.user

    context = {
        'qs': qs,
        'user': user,
    }

    return render(request,'idea/main.html', context)


def like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = Like.objects.get_or_create(user=user, post_id=post_id)
        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
            like.save()

        data = {
            'value': like.value,
            'likes': post_obj.liked.all().count()
        }
        return JsonResponse(data, safe=False)

    return redirect('idea:post-list')


def add_idea(request):
    if request.method == 'POST':
        form = IdeaForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('idea:post-list')
    else:
        form = IdeaForm()
    return render(request, 'idea/add_idea.html', {'form': form})

cproject/idea/templates/idea/add_idea.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Добавление идеи</title>
</head>
<body>
{% include 'idea/nav.html' %}
<div class="container mt-3">
    <div class="row">
        <h1>Добавить идею</h1>
    </div>
    <form action="{%  url 'idea:add_idea' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

      <button type="submit" class="btn btn-primary btn-block">Добавить</button>
    </form>

</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

cproject/idea/templates/idea/like_section.html
<form action="{% url 'idea:like-post' %}" method="POST" class="like-form" id="{{obj.id}}">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{obj.id}}">
                        <button class="btn btn-info like-btn{{ obj.id }}" type="submit">
                            {% if user not in obj.liked.all %}
                            Like
                            {% else %}
                            Unlike
                            {% endif %}
                        </button>
                    <div class="like-count{{ obj.id }}">{{obj.liked.all.count}} </div>
                </form> likes

cproject/idea/templates/idea/main.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Ваши предложения</title>
</head>
<body>
{% include 'idea/nav.html' %}
<div class="container mt-3">
    <h1>Список идей</h1>
    <div class="row">
        {% for obj in qs %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ obj.title }}</h5>
                <p class="card-text">{{ obj.body }}</p>
            </div>
            <div class="'card-footer text-muted">
                {{ obj.author }}
                <br/>
                {{obj.created_at}}


                <br/>
                {% include 'idea/like_section.html' %}
                <hr>
                <br/>

            </div>
        </div>
        {% endfor %}


    </div>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<script src="{% static 'idea/js/like.js' %}"></script>
</body>
</html>

cproject/idea/templates/idea/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'idea:post-list' %}">Главная</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'idea:add_idea' %}">
                        <button type="submit" class="btn btn-primary btn-block">Добавить идею</button>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>